version: '3.8'

services:
  # Servei 1: Nginx
  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_NAME}
    ports:
      - "${NGINX_PORT}:80"          # Mapeja el port extern al 80 intern
    restart: always

  # Servei 2: Backend
  backend:
    image: ${BACKEND_IMAGE}
    container_name: ${BACKEND_NAME}
    ports:
      - "${BACKEND_PORT}:8080"      # Mapeja el port extern al 8080 intern
    restart: always            

networks:
  default:
    name: ${NETWORK_NAME}           # Crea una xarxa virtual per a que es parlin per nom